In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
import pickle
import numpy as np
import matplotlib.pyplot as plt
import random
import os

## raw data

In [55]:
# get data, drop last NAN column, extract first two raws.
data = pd.read_table('../data/P123_20190224_133916.dat', sep=' ', encoding='utf-8',header=None)
data = data.drop(labels=36, axis=1)
# mean
M = (data.loc[0]+1000).tolist()
# standard deviation
S = (data.loc[1]+1000).tolist()
# feature data
data = data.drop(index=[0,1]).reset_index(drop=True)
data.shape

(67249, 36)

In [56]:
data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
0,-1.732012,1.712293,0.0,-2.034701,-2.458565,-1.654750,-2.002497,0.025670,0.820762,-1.005297,-1.306828,-0.371522,0.343728,2.553419,0.351094,0.027974,0.869308,0.213230,0.472986,0.228073,4.947509,4.940747,0.790944,0.784288,2.553953,2.759143,2.538070,2.771556,-1.149709,1.044148,-1.291510,0.892240,0.261481,1.230360,-0.691771,4.094313
1,-1.731961,1.712293,0.0,-2.034701,-2.458565,-1.646469,-1.996995,0.028309,0.857247,-0.839665,-1.304530,-0.594027,0.684582,2.553725,0.368481,0.029199,0.869487,0.160422,0.460895,0.239755,4.950694,4.958051,0.840452,0.833561,2.591646,2.755365,2.561883,2.763200,-1.189388,1.059722,-1.335063,0.761625,0.335940,-0.277523,0.359054,3.873393
2,-1.731909,1.711636,0.0,-2.034701,-2.458565,-1.648083,-1.991643,0.030013,0.891324,-0.899867,-1.300961,-0.421563,0.691267,2.517182,0.384545,0.029796,0.869640,0.135555,0.429068,0.259745,4.941473,4.949601,0.868210,0.863330,2.598304,2.761252,2.581077,2.765272,-1.189797,1.034744,-1.213312,0.788472,0.539627,-0.534792,1.002056,3.720319
3,-1.731858,1.710376,0.0,-2.034701,-2.458565,-1.643375,-1.985215,0.032856,0.932104,-1.112630,-1.294765,-0.515688,0.816702,2.516402,0.401023,0.030457,0.869846,0.127990,0.500233,0.255239,4.896569,4.900046,0.895341,0.892378,2.676272,2.902304,2.650020,2.893138,-1.052211,1.130507,-0.919787,0.899053,0.495633,0.160559,0.422761,4.098779
4,-1.731806,1.709745,0.0,-2.034701,-2.457952,-1.639023,-1.985008,0.033524,1.009953,-1.507243,-1.299273,-0.400387,0.771481,2.521734,0.417811,0.031403,0.870025,0.125469,0.494171,0.254724,4.765528,4.773487,0.925549,0.916342,2.822709,3.159169,2.799832,3.151294,-0.904923,1.247632,-0.938306,0.874178,0.455232,-3.330808,0.884475,2.670593

## save data per plane

In [ ]:
in_file='../data/'
out_file='../data_per_plane/'
listfile=os.listdir('../data')
plane=['P123','P124','P125','P126','P127']
for p in plane:
    DATA,M,S,number=pd.DataFrame(),pd.DataFrame(),pd.DataFrame(),0
    for i in listfile:
        if i.startswith(p):
            data = pd.read_table(in_file+i, sep=' ', encoding='gbk',header=None)
            data = data.drop(labels=36, axis=1)
            # mean
            m = pd.DataFrame(np.array((data.loc[0]+1000).tolist()).reshape(1,36))
            m.insert(0,'number',[number]*m.shape[0])
            M = pd.concat([M,m],ignore_index=True) 
            # standard deviation
            s = pd.DataFrame(np.array((data.loc[1]+1000).tolist()).reshape(1,36))
            s.insert(0,'number',[number]*s.shape[0])
            S = pd.concat([S,s],ignore_index=True) 
            # feature data
            data = data.drop(index=[0,1]).reset_index(drop=True)
            data.insert(0,'number',[number]*data.shape[0])
            DATA = pd.concat([DATA,data],ignore_index=True) 
            number=number+1
    DATA.to_csv(out_file+p+'_data.csv',index=False,sep=',')
    M.to_csv(out_file+p+'_mean.csv',index=False,sep=',')
    S.to_csv(out_file+p+'_sd.csv',index=False,sep=',')

In [105]:
listfile=os.listdir('../data')
DATA,M,S,L=pd.DataFrame(),pd.DataFrame(),pd.DataFrame(),[]
for i in listfile:
    if i.startswith('P123'):
        data = pd.read_table('../data/'+i, sep=' ', encoding='gbk',header=None)
        data = data.drop(labels=36, axis=1)
        # mean
        m = pd.DataFrame(np.array((data.loc[0]+1000).tolist()).reshape(1,36))
        M = pd.concat([M,m],ignore_index=True) 
        # standard deviation
        s = pd.DataFrame(np.array((data.loc[1]+1000).tolist()).reshape(1,36))
        S = pd.concat([S,s],ignore_index=True) 
        # feature data
        data = data.drop(index=[0,1]).reset_index(drop=True)
        DATA = pd.concat([DATA,data],ignore_index=True) 
        # length
        L.append(data.shape[0])

## new data frame

In [2]:
data = pd.read_csv('../data_per_plane/P123_data.csv', encoding='utf-8')
M = pd.read_csv('../data_per_plane/P123_mean.csv', encoding='utf-8')
S = pd.read_csv('../data_per_plane/P123_sd.csv', encoding='utf-8')

FileNotFoundError: [Errno 2] No such file or directory: '../data_per_plane/P123_data.csv'

In [4]:
data.head()

,number,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
0,0,-1.732013,1.627998,-1.116035,-2.706933,-2.659184,-2.612687,-2.670158,0.055802,0.749807,-2.914373,-2.102434,-0.456964,1.024642,2.337097,0.900550,0.069223,0.939846,-0.181490,0.196586,0.221355,4.104957,4.119176,0.790689,0.780243,2.478293,3.367638,2.446210,3.388407,-0.219481,0.989748,2.072308,0.253129,0.330973,0.766172,-1.587772,1.797304
1,0,-1.731962,1.627774,-1.116035,-2.671229,-2.659282,-2.595992,-2.652155,0.058947,0.770800,-2.807495,-2.089644,-0.624927,0.942908,2.314235,0.932634,0.067622,0.940114,-0.113666,0.228385,0.223716,4.061014,4.070022,0.825797,0.821790,2.697761,3.346549,2.667705,3.354251,-0.242399,0.947969,2.073712,0.127831,0.349229,0.812068,-1.947818,1.642888
2,0,-1.731912,1.627774,-1.116035,-2.628320,-2.659247,-2.562306,-2.666668,0.062394,0.793095,-2.767525,-2.099293,-0.459025,0.769351,2.314110,0.959606,0.066981,0.940420,-0.037019,0.229142,0.219377,4.033778,4.041988,0.858056,0.854958,2.837615,3.349981,2.809476,3.365585,-0.329673,0.842328,2.073712,-0.015522,0.287970,0.722603,-1.202504,2.390552
3,0,-1.731862,1.627774,-1.116035,-2.628320,-2.659612,-2.538233,-2.658709,0.064513,0.831189,-3.206882,-2.094251,-0.585839,0.981579,2.314648,0.989330,0.068034,0.940670,0.052732,0.202851,0.227355,4.039749,4.043938,0.884376,0.877601,2.868565,3.419655,2.833103,3.409443,-0.371370,0.784601,2.073712,0.252475,0.258080,0.612936,0.442171,13.009677
4,0,-1.731812,1.627774,-1.116035,-2.628320,-2.659612,-2.541910,-2.653678,0.066565,0.884376,-3.641232,-2.086120,-0.410156,0.711630,2.315874,1.014955,0.070195,0.940948,0.112581,0.211597,0.232289,4.030001,4.029873,0.907375,0.901408,2.845894,3.595214,2.823027,3.579476,-0.387021,0.746796,2.073712,0.324274,0.140072,0.555907,0.811992,6.903981

In [3]:
M.head()

,number,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
0,0,3771.344004,5000.425128,813.902235,0.594339,3651.434590,589.310207,709.628229,-0.241057,6.755172,-0.075147,18.075197,1.449955,-0.015777,0.219206,4.428620,-1.767443,-18.854774,-0.060510,1.951971,-0.116905,25.661706,25.607411,11.197671,11.252688,0.788730,0.775683,0.719593,0.679728,-14.786665,14.184914,358.640463,2.666907,-3.128211,-1.525959,-0.030151,-0.001622
1,1,3444.531250,4918.252243,0.000000,0.490531,3434.422226,495.382328,594.396857,-0.066386,7.830173,-0.023586,12.744777,1.217397,-0.010944,0.182992,6.401572,-4.409655,-38.003963,-0.764485,1.339129,-0.399419,25.421282,25.362367,13.641174,13.693194,1.212475,1.524890,1.137506,1.426107,-14.613103,14.624575,238.148398,2.731010,-3.007702,-1.141074,-0.030395,-0.001780
2,2,4137.906250,5824.864732,1115.506654,0.535417,3579.498969,530.721848,648.005232,-0.161974,8.332896,-0.055110,14.640923,1.342918,-0.010567,0.233082,5.349943,4.726052,-35.013723,-0.107685,1.884757,0.168799,24.761305,24.689934,13.928993,13.980696,0.906731,1.112690,0.785806,0.996031,-14.343363,13.929595,479.146450,2.578187,-3.489530,-1.272702,-0.048789,-0.016441
3,3,4128.312642,5089.237147,101.831314,0.595410,3176.022281,605.421046,704.563206,0.033856,7.030132,0.006527,19.630258,1.425887,-0.022633,0.223161,4.202273,-5.117740,-9.552948,-0.129985,1.918963,-0.368089,25.177104,25.128390,10.978691,11.044056,0.770991,0.395487,0.731405,0.300565,-14.660543,13.650558,359.043492,2.619800,-3.664398,-1.519141,-0.045408,-0.010599
4,4,3530.531250,4876.220893,0.000000,0.539647,3511.434863,543.407182,640.668204,-0.107292,7.105937,-0.002268,15.556056,1.383755,-0.013603,0.204059,5.350917,-1.665481,-14.183194,-0.839965,1.777402,-0.288252,25.693726,25.671873,12.101008,12.170187,1.110147,1.357825,1.091519,1.273424,-14.663263,14.588890,3.737553,-1.763818,2.833007,-0.044044,-1.604970,-4.030657

In [6]:
S.head()

,number,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
0,0,1243.116759,2640.154340,603.836105,0.127206,1373.671934,104.008358,144.725391,19.388791,4.806085,0.408945,6.198610,0.901489,0.029840,0.192223,6.305087,36.561687,102.334244,9.868968,3.808890,2.268993,3.089467,3.092245,9.267318,9.267629,2.033269,1.948335,2.030297,1.942691,2.503379,2.779970,421.639824,0.778917,1.417972,1.192571,0.012501,0.011008
1,1,1228.502141,1650.151601,0.000000,0.105825,1263.461212,105.496754,124.392904,32.972423,4.370806,0.383651,5.481118,0.606909,0.013220,0.144754,13.030126,37.891995,100.879781,7.292909,2.844981,1.967818,2.972964,2.973832,8.667922,8.665852,1.839392,2.025775,1.837868,2.021507,2.549351,2.351225,243.364192,0.448835,0.950490,0.800113,0.011323,0.009350
2,2,1141.466588,2412.216877,456.397542,0.135236,1376.217953,107.065908,155.395680,18.755836,6.287293,0.476934,5.558736,0.707334,0.021832,0.176283,7.195634,34.113525,97.795807,7.233077,3.690483,2.472397,4.259182,4.258411,11.141544,11.144802,2.447438,2.404934,2.440895,2.405003,2.912143,3.205574,409.841025,0.552126,0.957768,0.913528,0.012144,0.018434
3,3,1115.143269,2518.580575,56.496509,0.164691,1506.431744,137.212350,184.121091,21.023963,6.252047,0.453255,8.579325,0.967805,0.028157,0.205928,7.364401,32.950971,101.205702,6.598348,4.029424,2.125625,4.274632,4.278305,10.677353,10.678416,2.278047,2.205408,2.271606,2.197461,2.732615,3.818867,424.029708,0.737296,1.589459,1.403796,0.013167,0.012373
4,4,1197.541733,1794.307425,0.000000,0.119458,1426.216395,120.104070,139.131810,37.984368,4.007047,0.388584,7.015052,0.891330,0.016082,0.179206,14.588555,43.284596,112.849577,9.043703,3.486415,1.906875,2.772363,2.775061,8.149681,8.148723,1.936878,2.169008,1.934761,2.161128,2.757937,2.317046,1.310910,1.231990,1.432810,0.011211,0.012441,0.686229

In [81]:
# length of a series
sequence_length=[10,20,30,40,50,60,70,80,90,100]
# length of a test of a plane
lengths=data.groupby('number')['0'].count().tolist()
# batch size
batch_size=64
# 30 feature name
feature_name=data.columns.values.tolist()[1:31]
# label name
label_name='30'

batch_data=[]
batch_label=[]
# random series length
index_sequence_length=sequence_length[random.randint(0,len(sequence_length)-1)]
# which test
number = random.randint(0,len(lengths)-1)
for i in range(batch_size):
    index_row=random.randint(0,lengths[number]-index_sequence_length-1)
    d=data[data['number']==number].reset_index(drop=True).loc[index_row:index_row+index_sequence_length-1,feature_name].values.tolist()
    label=data[data['number']==number].reset_index(drop=True).loc[index_row+index_sequence_length-1,label_name]
    batch_data.append(d)
    batch_label.append([label])